Write-Host "Planned bootstrap steps:"
Write-Host "1. terraform -chdir=envs/dev init"
Write-Host "2. terraform -chdir=envs/dev plan"
Write-Host "3. terraform -chdir=envs/dev apply"
Write-Host "4. Build and push the backend container image"
Write-Host "5. Publish app/public to S3 or another static host and create app/public/config.js from config.js.example"
Write-Host "6. Copy helm/examples/aws-database-secret.yaml.example to a local secret manifest and fill in real DB values"
Write-Host "7. Configure kubectl for the EKS cluster"
Write-Host "8. kubectl create namespace demo"
Write-Host "9. kubectl apply -f <your-local-db-secret.yaml>"
Write-Host "10. helm upgrade --install snake-api .\\helm\\snake-api -n demo -f .\\helm\\values-aws.yaml"
