replicaCount: 1

image:
  repository: incode-snake-backend
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []

service:
  type: ClusterIP
  port: 8080
  targetPortName: http
  nodePort: null

ingress:
  enabled: false
  className: ""
  annotations: {}
  host: ""
  path: /
  pathType: Prefix
  tls: []

app:
  port: 8080
  corsOrigin: "*"
  leaderboardLimit: 10

db:
  createSecret: false
  secretName: ""
  existingSecretName: demo-api-db
  host: ""
  port: "5432"
  name: ""
  username: ""
  password: ""
  sslMode: disable

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 192Mi

monitoring:
  serviceMonitor:
    enabled: false
    interval: 15s
    scrapeTimeout: 5s
    path: /metrics
    additionalLabels: {}
