alertmanager:
  enabled: false

grafana:
  service:
    type: ClusterIP
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: monitoring

prometheus:
  service:
    type: ClusterIP
  prometheusSpec:
    retention: 12h
    scrapeInterval: 15s
    evaluationInterval: 15s
