image:
  repository: ghcr.io/your-user/incode-snake-backend
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

app:
  corsOrigin: "*"

db:
  createSecret: false
  existingSecretName: demo-api-db
  sslMode: require

monitoring:
  serviceMonitor:
    enabled: false
    additionalLabels:
      release: monitoring
