{{- if .Values.db.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snake-api.dbSecretName" . }}
  labels:
    {{- include "snake-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  host: {{ .Values.db.host | quote }}
  port: {{ .Values.db.port | quote }}
  dbname: {{ .Values.db.name | quote }}
  username: {{ .Values.db.username | quote }}
  password: {{ .Values.db.password | quote }}
{{- end }}
